server:
  port: 9101

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-service
  elasticsearch:
    uris: http://localhost:9200

authservice:
  secrets:
    key: ${JAVA_SECRETKEY}
    issuer: ${JAVA_ISSUER}
    exDate: 300000